### ISSUE TITLE
Usage of class HMSensor

### ISSUE THREAD

**Issue by dagobert** [danielperna84/pyhomematic#217] opened 2019-02-02 13:40 UTC
I have seen in sensors.py that you have the following classes:

```
class HMSensor(HMDevice):
    pass

class HMBinarySensor(HMDevice):
    pass
```

Since I am no python expert, I am not sure what they are doing. Some but not all of the other classes have these as a parameter. If it is some kind of inheritance than I would propose using them for something worth while.

We could "implement the functionality into them which all devices share. For HomematicIP devices for example we could use them to include HelperLowBatIP and HelperOperatingVoltageIP.

But as I said, I am not an expert on Python.

**Comment by danielperna84** [comment] 2019-02-02 19:31
If I recall correctly that's from the early days of pyhomematic. Back then most devices where implemented like the thermostats. All those helpers came later.  
The cleanest solution would actually be, to make a helper out of pretty much every parameter we know of. Then most of the time we would just inherit from those and set the channels per device type.

**Comment by dagobert** [comment] 2019-02-04 20:50
I agree. That should be the goal.

When it comes to generic device classes like you have right now (eg. HMSensor) I think there should be only a few very generic ones. Than it is easier to identify the functionality of a device more easy.

I would start on changing the code over the next weeks and send you PR if you are fine with that.

**Comment by danielperna84** [comment] 2019-02-04 21:10
Yes, that would be ok. I would suggest to make branches for every _section_ to minimize conflicts with possible arriving pull requests. So one branch for sensors, one for actors etc.

**Comment by dagobert** [comment] 2019-02-08 23:54
I will split my work into two parts. 

First I will try to "clean-up" the code, meaning that I will make use of more helpers and little generic "inheritance".  I will not change class names. That would be the ground-work for the second part.
In the second part I will  than start to rename classes as described in the other issue.

I have just another question for my better understanding:

`self.ATTRIBUTENODE.update({"LOW_BAT": [0]})`

Is the `[0]` the channel or related to the channel?
Can you tell my if I read the code correctly that standard HM devices have or have only one channel?

If so, using the current implementation of eg. `HelperRssiDevice` in a standard HM device would not work. I am asking this because I read this line in sensors.py:

`class ShutterContact(IPShutterContact, HelperSabotage, HelperRssiPeer):`

**Comment by danielperna84** [comment] 2019-02-09 00:11
> Is the `[0]` the channel or related to the channel?

Yes, `0` is the master-channel every device has. The battery info always is on channel `0`. Now if we have a switch-device with multiple channels, the list would be for example `[1,2]`. In Home Assistant they both should have the `LOW_BAT` attribute because it physically is the same device. So with this solution we can define, that switch-entities should be created for the channels `1` and `2`, and they both should look at channel `0` for the battery state.

> ...that standard HM devices have or have only one channel?
They always have at least channel `0` and `1`, most times a lot more. Some have up to ~ `20` channels. So in case of a switch actuator with multiple outputs there will (usually) will be one channel per output with the `STATE` parameter. The parameters are unique per channel. But there can be different paramters on one channel. For example a PIR sensor usually has the parameters `MOTION` and `BRIGHTNESS` on a single channel.
Have a look at [this](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf) documentation to get a better understanding of the concept.

**Comment by dagobert** [comment] 2019-02-09 13:00
I am using this issue to further ask questions about your code regarding my changes, ok?

In HMDevice you defined ELEMENT as returning `[1]`. In eg. `sensors.py` you sometimes use  `self.SENSORNODE.update({"VALVE_STATE": self.ELEMENT})`, sometimes  `self.SENSORNODE.update({"VALVE_STATE": [1]})` and sometimes you use

```
self.SENSORNODE.update({"VALVE_STATE": self.ELEMENT})
@property
    def ELEMENT(self):
        return [1]
```

(Of cause the particular Atribute VALVE_STATE might not have these many variations but I can find these three versions with different attributes in different classes.)

Aren't all of these the same in the end? Shouldn't there be better one way of doing it?

**Comment by danielperna84** [comment] 2019-02-09 15:32
They are similar. The ELEMENT-propery usually holds the main channels of the device. But as mentioned above, different paramters might be on different channels.

`self.SENSORNODE.update({"VALVE_STATE": self.ELEMENT})`
This can be used if the parameter-channels match the channels in `ELEMENT`. 
`self.SENSORNODE.update({"VALVE_STATE": [1]})`
This can be used when a sensor from a different channel should be included, or the parameter is not available on all channels.

Image a theoretical switch actuator with 2 channels (1 and 2). So it can be used to switch 2 _consumers_ on and off. Additionally it can measure the power consumption __only__ on channel 1. This would be constructed somewhat like this:

```python
class mySwitch(GenericSwitch):
    # self.WRITENODE.update({"STATE": self.ELEMENT})
    self.SENSORNODE.update({"POWER": [1]})
    @property
    def ELEMENT(self):
        return [1, 2]
```
Because the `GenericSwitch` subclasses `HelperActorState` the commented out line for the writenode is already added automatically. The problem is, that the `ELEMENT` property has the correct channels for the switches, but one too much for the sensor. That's why we override this with the actual channel mapping.
Also have a look at the [Switch](https://github.com/danielperna84/pyhomematic/blob/e298897c455340cd43c50e700d227322e4ed735f/pyhomematic/devicetypes/actors.py#L191) class. Here you can see why this is done. There are many different devices with different channels. By subclassing `Switch` we get the `ELEMENT` property pre-filled with the correct channels depending on which device variant is being used. __But:__ because of that we can't use `ELEMENT` anymore for sensors etc., because they usually are different.

**Comment by dagobert** [comment] 2019-02-09 23:03
So, if I understand correctly:

`ELEMENT` is defined in eg. HMDevice as `[1]`. For this reason whenever there are no more channels than this we can use `self.ELEMENT` to assign the channel to a NODE. Otherwise we need to use the channel number.

`ELEMENT` is supposed to return an array of all the channels.

I hope this is right. Thank you for being so patient and are explaining so much.

**Comment by danielperna84** [comment] 2019-02-09 23:31
Mostly it's defined in the specific classes since the channels are very individual. A rather complex example is the HMW IO switch in actors.py. It detects the channel configuration and sets everything accordingly.
But yes, in general your statement is correct.

**Comment by danielperna84** [comment] 2019-02-19 21:25
Closing this issue since you are done with `sensors.py`.

**Closed by danielperna84** 2019-02-19 21:25 UTC
