### ISSUE TITLE
Jsonrpc Port ignored

### ISSUE THREAD

**Issue by wildi1** [danielperna84/pyhomematic#331] opened 2020-09-23 21:02 UTC
**Home Assistant version (if applicable):**
0.115.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
homematic:
  local_ip: xxx.xxx.xxx.xxx
  local_port: 20000
  interfaces:
    Funk:
      host: xxx.xxx.xxx.xxx
      port: 18001
      callback_ip: xxx.xxx.xxx.xxx
      callback_port: 20000
      resolvenames: xml
      jsonport: 18000
      username: Admin
      password: !secret
  hosts:
    ccu3:
      host: xxx.xxx.xxx.xxx
      port: 18001
      username: Admin
      password: !secret
```
**Describe the bug**
Parameter jsonport is ignored => ERROR (SyncWorker_4) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: <urlopen error [Errno 111] Connection refused>

**To Reproduce**
1. When Homematic is listening e.g. port 18000 you are unable to connect

**Expected behavior**
It should connect 

**Additional context**
I'm Running my homematic offshore behind an LTE Router, so i have build up a bidirectional ssh tunnel because of the missing public ip. In my case I map the port 18000 to homematics port 80 but the connection does not work. In following logfile you can see, that port 80 instead of 18000 is used.

**Logfile**
2020-09-23 22:55:35 DEBUG (SyncWorker_12) [pyhomematic._hm] RPCFunctions.jsonRpcPost: API-Endpoint: http://xxx.xxx.xxx.xxx:80/api/homematic.cgi
2020-09-23 22:55:35 ERROR (SyncWorker_12) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: <urlopen error [Errno 111] Connection refused>
2020-09-23 22:55:35 WARNING (SyncWorker_12) [pyhomematic._hm] ServerThread.jsonRpcLogin: Unable to open session.

**Comment by danielperna84** [comment] 2020-10-02 15:55
I don't see why it's not working. The HA-component supports the parameter ([here](https://github.com/home-assistant/core/blob/576fbbe0be3b684618e453fc0bce1809673663cd/homeassistant/components/homematic/__init__.py#L222)), and in pyhomematic we even switch to https in case of port `443` [here](https://github.com/danielperna84/pyhomematic/blob/0944b85462d34c8dbaa995ae6788e106c3b4683b/pyhomematic/_hm.py#L369). So it _should_ work. 🤔

**Comment by wildi1** [comment] 2020-10-02 19:58
Thank you for your answer. The resolvenames option setted to xml was just another try. I had it to json before, but posted my last config here. It was bit late:-)

Can you reproduce the behaviour I descriped on your own by setting a different jsonport? Or does it work to you?

**Comment by hanzoh** [comment] 2021-01-07 10:35
I added the jsonport functionality back then when I played with running CCU in a Docker container.
As that was unstable, I moved to RaspberryMatic running in a VM.
But as RaspberryMatic is now available as a Docker container (still WIP), I gave it another try.

I can confirm, that the jsonport config entry is not honored:

```txt
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] ServerThread.getAllSystemVariables: Getting all System variables via JSON-RPC
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Method: Session.login
2021-01-07 11:32:37 DEBUG (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: API-Endpoint: http://192.168.1.10:80/api/homematic.cgi
2021-01-07 11:32:37 ERROR (SyncWorker_14) [pyhomematic._hm] RPCFunctions.jsonRpcPost: Exception: HTTP Error 308: Permanent Redirect
2021-01-07 11:32:37 WARNING (SyncWorker_14) [pyhomematic._hm] ServerThread.jsonRpcLogin: Unable to open session.
```

```yaml
homematic:
  interfaces:
    ip:
      host: 192.168.1.10
      port: 2010
      resolvenames: json
      jsonport: 8082
      username: Admin
      password: x
    groups:
      host: 192.168.1.10
      port: 9292
      resolvenames: json
      jsonport: 8082
      username: Admin
      password: x
      path: /groups
  hosts:
    ccu:
      host: 192.168.1.10
      port: 2001
      username: Admin
      password: x
```

**Comment by nicx** [comment] 2021-01-07 15:27
I am also testing the new docker container with similar problem, but I don't think its related to the interfaces (where the jsonport option works) but to the hosts (where its not possible to set a jsonport). If I comment out the hosts, I don't get any errors and the name resolving is working as expected.

**Comment by danielperna84** [comment] 2021-01-07 21:31
> but I don't think its related to the interfaces (where the jsonport option works) but to the hosts (where its not possible to set a jsonport)

Not __that's__ a really important detail that has not been communicated when this issue was raised.

So this issue probably will be fixed by adding a `jsonport` option [here](https://github.com/home-assistant/core/blob/0426b211f62a618f7277b9f178e832309699fbc5/homeassistant/components/homematic/__init__.py#L141), and then including the value [here](https://github.com/home-assistant/core/blob/0426b211f62a618f7277b9f178e832309699fbc5/homeassistant/components/homematic/__init__.py#L237) when adding the remote.

**Comment by wildi1** [comment] 2021-01-07 21:44
In my case, the jsonport in the interface section did not work. That was the reason for opening that issue.

**Comment by danielperna84** [comment] 2021-01-07 21:52
@wildi1 

So in your case the device names don't get resolved, correct?

**Comment by wildi1** [comment] 2021-01-07 22:18
Yes, that was my problem when I opened the issue.
Now I have changed my setup of homematic and home assistant so that I don‘t need a different jsonport anymore.

**Comment by nicx** [comment] 2021-01-08 06:51
> > but I don't think its related to the interfaces (where the jsonport option works) but to the hosts (where its not possible to set a jsonport)
> 
> Not **that's** a really important detail that has not been communicated when this issue was raised.
> 
> So this issue probably will be fixed by adding a `jsonport` option [here](https://github.com/home-assistant/core/blob/0426b211f62a618f7277b9f178e832309699fbc5/homeassistant/components/homematic/__init__.py#L141), and then including the value [here](https://github.com/home-assistant/core/blob/0426b211f62a618f7277b9f178e832309699fbc5/homeassistant/components/homematic/__init__.py#L237) when adding the remote.

@danielperna84 just tried the modification locally and the error is gone, it works like a charm. So yes, these two small jsonport changes are enough to get the host working! :) would you integrate this in your code?

**Comment by nicx** [comment] 2021-03-07 20:09
@danielperna84 any news when this small fix will be integrated?

**Comment by danielperna84** [comment] 2021-03-07 20:14
@nicx 
I'm pretty busy currently _offline_. Feel free to fork Home Assistant and submit a pull request for the patch. Because it's a bugfix it will probably published in a bugfix release pretty soon. 👍

**Comment by nicx** [comment] 2021-03-08 06:29
I just tried it, hopefully I did everything correct (I am not a developer) and it will be merged soon :)

**Comment by nicx** [comment] 2021-04-19 19:12
just fyi: sadly the merge request was declined. the who,e component has to be rewritten to match the new config ui flow. hopefully @danielperna84 or any other developer has the time to do this in future.

**Comment by danielperna84** [comment] 2021-04-19 19:25
@nicx 

I'm working on the foundation module. But I need someone to do the Home Assistant part (at least the basics in terms of UI configuration). [Here's](https://github.com/danielperna84/hahomematic/issues/1) my issue where I'm asking for help.

**Comment by danielperna84** [comment] 2021-05-28 22:33
[hahomematic](https://github.com/danielperna84/hahomematic/blob/7c8c8c7c79b1de0db9f3c20e20c03dd0b5a710b5/hahomematic/client.py#L74) can do this, and as the current integration based on pyhomematic won't get this feature (see the closed PR mentioned above), I'm closing this issue. So now we need contributors to get a new integration based on hahomematic.

**Closed by danielperna84** 2021-05-28 22:33 UTC

**Comment by julian-wendt** [comment] 2021-11-01 17:37
@wildi1 I would love if you could post the changes you made to your setup of home assistant and homematic. I'm facing the exact same problems and don't want to do manual changes to the code ...

**Comment by wildi1** [comment] 2021-11-04 08:24
@julian-wendt I don't use pyhomematic on a different json port anymore. So therefore I stopped searching a solution for this problem. Sorry and best wishes :)

**Comment by Holzweg63** [comment] 2021-11-25 22:05
@julian-wendt : Thank you, saved my day! Your solution worked for me (docker) beside one remaining error in "Getting all system variables via JSON-RPC". 
I've added "jsonport: port" also to the "hosts:" section of  "configuration.yaml" and the error was gone!

btw. I'm new to HA and can't understand why such a small but important patch could be rejected?
