### ISSUE TITLE
Retry connection if CCU is not available during startup of Home Assistant

### ISSUE THREAD

**Issue by hanzoh** [danielperna84/pyhomematic#141] opened 2018-06-29 08:30 UTC
I have already seen the issue regarding a reconnect if the CCU is restarted and Home Assistant is not.
But the reconnect service does not work when the CCU was not available during startup of Home Assistant:

```
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic.connection] HMConnection: Creating server object
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] ServerThread.__init__
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] __init__: Creating proxies
2018-06-29 10:00:54 INFO (SyncWorker_17) [pyhomematic._hm] Creating proxy ip. Connecting to http://192.168.1.223:2010
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] LockingServerProxy.__init__: Getting local ip
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] LockingServerProxy.__init__: Got local ip 192.168.1.223
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] RPCFunctions.__init__
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] RPCFunctions.__init__: iterating proxy = homeassistant-ip
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] RPCFunctions.__init__: devices_raw = []
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] RPCFunctions.createDeviceObjects: iterating interface_id = ip
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] ServerThread.__init__: Setting up server
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] ServerThread.__init__: Registering RPC functions
2018-06-29 10:00:54 INFO (Thread-3) [pyhomematic._hm] Starting server at http://0.0.0.0:45831
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] ServerThread.proxyInit: init('http://192.168.1.223:45831', 'homeassistant-ip')
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] proxyInit: Exception: [Errno 111] Connection refused
2018-06-29 10:00:54 WARNING (SyncWorker_17) [pyhomematic._hm] Failed to initialize proxy
2018-06-29 10:00:54 CRITICAL (SyncWorker_17) [pyhomematic.connection] Failed to start server
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic.connection]
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] ServerThread.stop: init('http://192.168.1.223:45831')
2018-06-29 10:00:54 DEBUG (SyncWorker_17) [pyhomematic._hm] proxyInit: Exception: [Errno 111] Connection refused
2018-06-29 10:00:54 WARNING (SyncWorker_17) [pyhomematic._hm] Failed to de-initialize proxy
2018-06-29 10:00:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component homematic
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 547, in proxyInit
    (callbackip, callbackport), interface_id)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 421, in __request
    return parent._ServerProxy__request(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/connection.py", line 74, in start
    self._server.proxyInit()
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 552, in proxyInit
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 568, in stop
    proxy.init(remote)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 421, in __request
    return parent._ServerProxy__request(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/local/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/homematic/__init__.py", line 333, in setup
    homematic.start()
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/connection.py", line 79, in start
    self._server.stop()
  File "/config/deps/lib/python3.6/site-packages/pyhomematic/_hm.py", line 574, in stop
    raise Exception
Exception
```

The hue component does this for example:
https://github.com/home-assistant/home-assistant/blob/26590e244ced1b67792bac8fdd5fc81ac446dba1/homeassistant/components/hue/bridge.py#L60

Could this be implemented in pyhomematic or is that something the Home Assistant component should do?

**Comment by danielperna84** [comment] 2018-06-29 14:12
This would be done in Home Assistant, pretty much the same way like the Hue component does it.

**Comment by hanzoh** [comment] 2018-06-29 15:07
Okay, but this exceeds my python and asyncio skills, unfortunately.
Would this be an extensive rewrite of the component or is that more of a smaller change?

**Comment by danielperna84** [comment] 2018-06-29 15:29
I acutally think this isn't even worth the effort. It won't be often that you restart HASS and the CCU at the same time. The only case I can think of is with a power outage and the CCU takes longer to reboot than the HASS machine.

**Comment by hanzoh** [comment] 2018-07-12 09:13
The use case is there when running CCU and HASS in docker containers and you restart both (docker upgrade, server reboot). Even when first setting things up, wouldn't it be better to catch the Exception that the CCU is not reachable and not put the trace into the HASS log?

**Comment by danielperna84** [comment] 2018-07-13 14:56
The exception is raised so HASS can react on it. If it wasn't raised, HASS would just passthrough the log and think everything is ok. We have an issue about [custom exceptions](https://github.com/danielperna84/pyhomematic/issues/24), which would be pretty much what the hue component also raises. By controlling the exception type we could make HASS react better to whatever happens. It just hasn't been a priority until now since it doesn't matter in most setups. Of course it can be done somehow. But even with your setup I'm sure there's actually a way of telling Docker in which order containers should be started if they depend on each other. After all the problem is not HASS/pyhomematic. It's Docker that starts the containers with a timing that doesn't meet the requirements of HASS. Making HASS take care of such Docker-Problems doesn't fix the root-issue.

**Comment by hanzoh** [comment] 2018-07-26 14:35
Unfortunately, there are no dependencies in Docker, you can't set up something as in init.d or systemd.
I have tried some hacks in __init__.py of the HASS homematic component, but catching the Exception there is not enough because pyhomematic reacts on the Exception and stops the proxies.
I have now a working state that does exactly what I need (https://github.com/danielperna84/pyhomematic/blob/649224c9b4ae4f75d2b807c2d706bcdc22f341fa/pyhomematic/_hm.py#L547):

`
            tries = 0

            while True:
                try:
                    proxy.init("http://%s:%i" %
                               (callbackip, callbackport), interface_id)
                    LOG.info("Proxy initialized")
                    break
                except Exception as err:
                    retry_delay = 2 ** (tries + 1)
                    tries += 1
                    LOG.error("Error connecting to the CCU. Retrying "
                                 "in %d seconds", retry_delay)

                    time.sleep(retry_delay)

                    continue
`

This will hold HASS startup for as long as the CCU comes back online, which is exactly what the zwave component does as well. When it cannot detect the USB stick, it cannot setup the component and HASS won't continue to start.
Waiting for the CCU to come online before setting up entities is also helpful if automations etc depend on it.

**Comment by danielperna84** [comment] 2018-07-26 14:52
Does the zwave component have some sort of `maxtries` option? I understand why this can be important. But I don't thinks it is good to have a component that would block _everything_ for an unlimited time. Waiting for 1-2 minutes could be acceptable. But personally I have devices from very different vendors. And I would definitely prefer a running subset of automations instead of everything to be dead just because the CCU got stuck. Imagine people having their home security system with Door-Sensors via the Xiaomi Gateway. It would be bad if those wouldn't do their job just because the HomeMatic thermostats don't work because the CCU has a problem.

**Comment by danielperna84** [comment] 2018-09-16 21:17
I have put some thought into this. Starting with [0.1.46](https://github.com/danielperna84/pyhomematic/pull/167) there's no more exception HASS could work with. The result of this is, that the pyhomematic RPC-Server (and the Proxy-object that talks to the CCU) will be started no matter what.
I haven't tested it, but if I'm not mistaken it will be possible to startup HASS now without the connected CCU. But because of the existing server and the proxy-object being available, the `homematic.reconnect` service in HASS should be able to load the entities even after the HASS startup.

In the long run I thought of some architectural changes. The component should always just start the server, and then handle the Proxy-init based on the configuration itself instead of letting pyhomematic do all this. Right now pyhomematic does everything. By dividing this up into multiple independent tasks, we could eventually end up with an additional service like `homematic.add_interface`, where we could add a CCU even at runtime. And of course this would also enable us to add the logic to HASS what to do when a host is not up yet during startup.

I'll have to keep thinking about this. Just wanted to share the idea I currently have.

**Comment by danielperna84** [comment] 2021-05-28 22:39
hahomematic includes the ability to detect disconnected _clients_, as shown [here](https://github.com/danielperna84/hahomematic/blob/7c8c8c7c79b1de0db9f3c20e20c03dd0b5a710b5/example.py#L78) in the example.

Apart from that, the (new) Home Assistant integration has to handle the general connectivity-problems. This is required anyways for integrations that aim to receive the GOLD-status.

Closing this issue, as it will be handled in the new integration eventually.

**Closed by danielperna84** 2021-05-28 22:39 UTC
