### ISSUE TITLE
Unknown Parameter for value key: OPERATING_VOLTAGE

### ISSUE THREAD

**Issue by MarpleA** [danielperna84/pyhomematic#349] opened 2020-11-01 20:49 UTC
Hi,

in Home Assistant I get the following error message:
`HMGeneric.getValue: OPERATING_VOLTAGE on xxxxxxxxxx:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>`

The Device is a Weather Station Plus and this happens not only at start up but many times - currently, 10min after restart 11 times.

I guess the weather station doesn't have this sensor. So is it possible to remove it from the code?

Best

**Comment by danielperna84** [comment] 2020-11-02 17:12
> So is it possible to remove it from the code?

Probably. Let's see if someone who has the device is willing to fix this. 👍

**Comment by MarpleA** [comment] 2020-11-03 09:31
Is there any way I can support on fixing this?

**Comment by RAYs3T** [comment] 2020-11-20 16:27
Hey I also get something similar in Home Assistant, but not with the Weather Station.

```

    HMGeneric.getValue: LOW_BAT on 0000DBE99724AA:0 Exception: <Fault -5: 'Unknown Parameter value for value key: LOW_BAT'>
    HMGeneric.getValue: RSSI_DEVICE on 0000DBE99724AA:0 Exception: <Fault -5: 'Unknown Parameter value for value key: RSSI_DEVICE'>
    HMGeneric.getValue: OPERATING_VOLTAGE on 00155A499CF06C:0 Exception: <Fault -5: 'Unknown Parameter value for value key: OPERATING_VOLTAGE'>
    HMGeneric.getValue: LOW_BAT on 00155A499CF06C:0 Exception: <Fault -5: 'Unknown Parameter value for value key: LOW_BAT'>
    HMGeneric.getValue: RSSI_DEVICE on 00155A499CF06C:0 Exception: <Fault -5: 'Unknown Parameter value for value key: RSSI_DEVICE'>
```

`00155A499CF06C` is a `HmIP-SWDM` (magnetic door window contact) device tho.

What kind of information can we get for you?
I am also a developer, so I'm happy with submitting something. I basically just need some sort of explanation whats going on here. I have the device on hand and could test whatever you want.

This is properly better placed in a full blown issue (will create one later..)

**Comment by danielperna84** [comment] 2020-11-20 17:43
> I basically just need some sort of explanation whats going on here

The problem is that the `HmIP-SWDM` is using the class [IPShutterContact](https://github.com/danielperna84/pyhomematic/blob/bf96419590881ba804246895b1d740d53332eadf/pyhomematic/devicetypes/sensors.py#L103), which inherits from [SensorHmIP](https://github.com/danielperna84/pyhomematic/blob/bf96419590881ba804246895b1d740d53332eadf/pyhomematic/devicetypes/sensors.py#L44), which inherits from [HelperOperatingVoltageIP](https://github.com/danielperna84/pyhomematic/blob/bf96419590881ba804246895b1d740d53332eadf/pyhomematic/devicetypes/helper.py#L57), which defines `OPERATING_VOLTAGE` as a parameter on channel `0`. As a result, Home Assistant asks the CCU (only once during startup) what the value for this parameter is to get the current value. Since your device doesn't have the parameter, the CCU responds with the error. This can be ignored because it doesn't really cause any harm, yet users seem to be annoyed by it. 🙄 So to fix this either a new super-class without the inheritance of the helper is required, or within the `__init__` the parameter has to be popped out.

The problem with this might be, that other devices using the same class may actually have that parameter. So then these users will mention the missing parameter. Effectively this is a constant hunt for parameters which some users want removed because their device doesn't have it, and others want them added because their device has it.

**Comment by Knechtie** [comment] 2021-04-13 18:19
I have the weather station plus and can confirm that there is no operating voltage (displayed in the CCU) and I also get error messages in the logs.

Inheriting from `SensorHmIPNoVoltage` instead of `SensorHmIP` should do the thing, am i right?
I can test it and do a PR if needed :thumbsup:

**Comment by danielperna84** [comment] 2023-09-10 16:38
This should be fixed with the [new integration](https://github.com/danielperna84/custom_homematic).

**Closed by danielperna84** 2023-09-10 16:38 UTC
Labels: help wanted
