### ISSUE TITLE
Blind control not showing correct cover level

### ISSUE THREAD

**Issue by lud-hu** [danielperna84/pyhomematic#241] opened 2019-04-24 19:42 UTC
**Home Assistant version (if applicable):**
0.91.1

**Describe the bug**
When controlling the blind (HMIP-BROLL) via home assistant and setting e.g. 50% level it is working fine and the state in HA switches to 50%.
When controlling the blind via the switch on the HMIP-BROLL, the state in HA switches to 100% or 0% and nothing in between.
But the correct level is available and transmitted to HA, but I guess not in the right place:

`2019-04-24 21:22:47 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=1234:3, interface_id=homeassistant-ip, key=LEVEL, value=0.24`
`2019-04-24 21:22:48 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=1234:4, interface_id=homeassistant-ip, key=LEVEL, value=1.0`
`2019-04-24 21:22:48 DEBUG (Thread-2) [homeassistant.components.homematic] 1234 received event 'LEVEL' value: 1.0`

As you can see in the log the correct level is present in the address=1234:3 level (0.24), but not in the address=1234:4 level (1.0). pyhomematic should tell HA to take the 24% as the new level.
Since I'm new to homematic I don't get the difference between the :3 and :4 address - I hope you can help.

Thanks for this great pyhomematic!

**Comment by danielperna84** [comment] 2019-04-24 21:26
Since I don't own such devices I'll tag this as _help wanted_, so anyone with such a device can participate in fixing this. 👍

**Comment by lud-hu** [comment] 2019-04-25 05:17
Can you give me sme hints on how to debug and approach this? I'd be happy to help! :)

**Comment by lud-hu** [comment] 2019-04-25 18:04
It looks like that it is kind of a bug in the homematic firmware, but it should be possible to get the current level out of channel 3 instead of channel 4 that is currently used by pyhomematic:
https://homematic-forum.de/forum/viewtopic.php?f=58&t=47868

**Comment by danielperna84** [comment] 2019-04-25 18:27
That would be a hack to fix something that is broken in the device. Implementing such a fix could potentially break other blind-actors that don't have that problem. On top of that, it somehow has to be detected that the problem is present. I doubt this can be achieved without great impact on the startup performance. Especially given that HomeMatic IP devices are known to cause problems when looking at their configuration details. Have a look at [this](https://github.com/danielperna84/pyhomematic/issues/219) issue for more information about that.

> Can you give me sme hints on how to debug and approach this? I'd be happy to help! :)

Have a look at [example.py](https://github.com/danielperna84/pyhomematic/blob/master/example.py) and 8actors.py](https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/actors.py). You would have to modify the class that your device inherits its features from.

**Comment by lud-hu** [comment] 2019-04-26 17:40
Do you know an easy way to test the idea I have for fixing this?
I can't get the pyhomematic Code to be overridden by my Code in home assistant environment (I thought I can just out it in as a custom components). :(

**Comment by danielperna84** [comment] 2019-04-26 18:18
Ideally you should set up a development VM completely separate from your productive Home Assistant. You can use [these](https://developers.home-assistant.io/docs/en/development_environment.html) instructions on how to set up a development environment. You can't / shouldn't do that with a custom component. Modify the existing component.

**Comment by lud-hu** [comment] 2019-04-27 08:48
OK Thank you!

I'm currently testing a few ways on how to solve this and I have a question:
https://github.com/danielperna84/pyhomematic/blob/8b91f3e84c83f05d289c740d507293a0d6759d8e/pyhomematic/devicetypes/generic.py#L330
Shouldn't the channel parameter be used as a override when it is handed in to _getNodeData()? Or do I understand it wrong and it has another functinality? What is this channel parameter for?

If this would be the case, I could just override the get_level() in IPKeyBlind with using channel 3.
It does not seem to be a bug per se in the HmIP-Broll, it seems to be always the case that the level has to be set with channel 4, the result is than stored in channel 3 (see [docs](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf)). The "sync" to channel 4 just seems to be buggy and just work in some circumstances.

**Comment by danielperna84** [comment] 2019-04-27 09:14
> Shouldn't the channel parameter be used as a override when it is handed in to _getNodeData()?

Yes. If you don't provide a channel, then a default value (`nodeChannelList[0]`)  is being used. It's for simpler devices where this way it's possible to just not specify a channel and it still works.

> If this would be the case, I could just override the get_level() in IPKeyBlind with using channel 3.

Yes. But in the thread you have mentioned it's stated, that this problem only appears with devices where _Expertenmodus_ has been toggled. At least to me it seems as if everything works fine for _regular_ users. And the highest priority is to retain functionality for the majority of users.

As far as I understand, the extra channel for your device is a [virtual actor channel](https://www.elv.de/elektronikwissen/virtuelle-homematic-aktorkanaele-und-ihre-verknuepfungslogik.html) that is misbehaving. Not everybody has those activated, and implementing a fix that uses them wouldn't work for most people. So there needs to be some mechanism to actually figure out if the fix is needed. After all the device itself has been supported for a while, and until yet nobody has reported this problem.

Try to implement a fix, and then we'll see if anyone with the same device experiences problems. 👍

**Comment by lud-hu** [comment] 2019-04-27 09:36
> Yes. If you don't provide a channel, then a default value (nodeChannelList[0]) is being used.

The way it is implemented currently, channel parameter is only used if nothing is in nodeChannelList. I will include this fix in my PR.

> At least to me it seems as if everything works fine for regular users.

Yes but according to the specification the level is always maintained in channel 3, therefore it should not make a problem for other users.
To be honest, I don't really need the expert mode but I can't turn it off without the ccu2 gui (I'm only using a docker container xml api).

I will create a PR that fixes the problem at least when used from the pyhomematic command line. In home assistant it is still not shown correctly but this has nothing todo with this framework anymore I guess.

**Comment by danielperna84** [comment] 2019-04-27 10:01
> The way it is implemented currently, channel parameter is only used if nothing is in nodeChannelList.

Huh? The line is: `nodeChannel = channel if channel is not None else nodeChannelList[0]`
According to my understanding that means:  
- Use _channel_ if it is provided with the call __and__ it's not `None`
- Otherwise use the value of `nodeChannelList[0]`

The other case is in the line below, which will be used if `nodeChannelList` only has a length of 1, so only one channel is defined for the device. If only one channel is available, then overriding the channel wouldn't make sense.

> Yes but according to the specification the level is always maintained in channel 3, therefore it should not make a problem for other users.

I don't think you can rely on the specification too much. I for example have a HMIP-PSM, which is a switch. The transmitter is on channel 2, but in pyhomematic channel 3 (the first virtual receiver) has to be used in order for the device to be controllable.  
For your HMIP-BROLL the transmitter is on channel 3, and the first virtual receiver on channel 4. And when it has been implemented (I don't know by whom), channel 4 has been used. So to me it seems as if in terms of channel functionality our devices are comparable. And looking at other devices this scheme is also used. It's always the first virtual receiver channel after the channel that _should_ be the correct one that works in pyhomematic (XML-RPC). 🤔 

Anyways, we'll see what other BROLL-users report about your change. 👍

**Comment by lud-hu** [comment] 2019-04-27 14:06
Yes, but if an override is handed in it makes sense to use it and it doesn't matter how many other values are present I think?

Hm unfortunately I can't get it working in home assistant even with my proposed fix. HASS is not using the get_level() or set_level() methods of pyhomematic, but is using some one logic if I see it right.

**Comment by danielperna84** [comment] 2019-04-27 14:40
> Yes, but if an override is handed in it makes sense to use it and it doesn't matter how many other values are present I think?

Yeah, makes sense. Although I'n not sure if other parts of the code might rely on it working this way. 🤔 

> HASS is not using the get_level() or set_level() methods of pyhomematic, but is using some one logic if I see it right.

A callback function is used. The CCU / Homegear sends events to HASS. They are handled [here](https://github.com/home-assistant/home-assistant/blob/c174b83f5408124fc7834e8282969a1e8f9cca16/homeassistant/components/homematic/__init__.py#L564). Which is actually the biggest problem you might be facing. The entity in HASS is pretty much bound to a single channel. It's not built in a way that the state is received for channel a, but _written_ on channel b. In the HASS ecosystem those would be two separate entities, where one would be a read-only representation of the device-state, the other a write-only entity to modify the state. But that would be pretty useless.

**Comment by lud-hu** [comment] 2019-04-30 17:14
> A callback function is used. The CCU / Homegear sends events to HASS. They are handled here. Which is actually the biggest problem you might be facing.

After some thinking and trying I given up whit adapting the homematic component in a meaningful way. Big changes would be necessary that would never be merged into the project.
I now ended up "hacking" the __init__.py:_subscribe_homematic_events() so that it subscribes to channel 3 instead of 4 for all of my blinds. Built-In HASS components can simply be overriden by copying them to the custom_components folder. 
Just if someone will ever run into the same problem... :)

Thanks anyway!

**Comment by basekk** [comment] 2019-11-08 03:21
> Just if someone will ever run into the same problem... :)

lud-hu, I did run into the same issue.
The HA sliders are behaving strange with HmIP-FROLL and -BROLL - just as you described in your entry post. The status is changing from to 0% to 100% whenever stopped at or sent to values  in between. 

How did you solve this issue? 

I'm running a Home Assistant 0.101.2. on HassOS 2.12, HomeMatic is running on CCU3.
Any would be highly appreciated.

**Comment by lud-hu** [comment] 2019-11-12 16:17
Hi @basekk,

sorry for the late response.
As described, I added some lines to init.py:_subscribe_homematic_events() of the homematic component (you can just copy it to your configuration to overwrite it):

```
        # Set callbacks
        for channel in channels_to_sub:
            # DIRTY-HACK
            # Check if the device is any of my covers and if the channel to subscribe is 4
            # then change it to 3:
            if (channel == 4) and ((self._name == "001118...") or (self._name == "001118...") or (self._name == "001118...")):
                channel = 3
```
You can find the file here: https://github.com/home-assistant/home-assistant/blob/5f177fa42e48f298400b45725926da6f2ffb8e72/homeassistant/components/homematic/__init__.py#L1003

**Comment by lud-hu** [comment] 2020-01-18 22:13
Just as a heads-up if someone wants to make the same changes:
In the current homematic component version (hass 0.104.2) the change has to be made in entity.py:161:

https://github.com/home-assistant/home-assistant/blob/0.104.2/homeassistant/components/homematic/entity.py#L161

**Comment by mtdcr** [comment] 2020-07-02 13:18
> > If this would be the case, I could just override the get_level() in IPKeyBlind with using channel 3.
> 
> Yes. But in the thread you have mentioned it's stated, that this problem only appears with devices where _Expertenmodus_ has been toggled. At least to me it seems as if everything works fine for _regular_ users. And the highest priority is to retain functionality for the majority of users.

That conclusion was wrong: Expert mode only changes the display of the CCU's WebUI. It does not change any values reported by the XML-RPC API. Therefore it's broken for everybody, including _regular_ users.

**Comment by leinich** [comment] 2020-08-26 09:35
Seems to me that updating the ccu3 to firmware 3.53.26 fixed the issue.
At least HA 0.114.0 with CCU3 3.53.26 is working.
Can someone confirm? @mtdcr @lud-hu @basekk

**Comment by alexanderlink** [comment] 2020-08-31 08:34
@leinich After upgrading my CCU3 to 3.53.26 some HmIP-BROLLs (latest firmware) regularly have communication issues with CCU3 and also Home Assistant shows them as "unavailable" then. I already created a ticket at eq-3.

Besides that it doesn't seem to fix the issue with the incorrect cover level for me. When I use the BROLL push buttons directly Home Assistant still shows 100 or 0. (I saw some new (for me) configuration options in the BROLL configuration in CCU3, did not have time yet to check if this might fix it)

**Comment by rbloehm** [comment] 2020-12-18 18:47
Same issue here with the HMIP-BBL (blind actuator with position+tilt) + CCU3. 
Just want to make sure that this issue is kept open a little longer.

Like everyone else in this thread I tried all kinds of combinations (with/without expert mode, all kinds of resets, ...), I even did something not mentioned here before: I changed the original direct link of the HMIP-BBL which uses expert mode to a simpler one (non-expert), but without any luck.

I spent quite some time in the logs and it all makes sense now. Truth seems to be:

- Channel 4 should not be used at all for these devices for reading the state, only for setting values
- Channel 3 has to be used for getting current position/tilt
- It's not a bug, but intended. In fact, what I see in various forums is that more IP devices are about to change to this kind of behaviour and we should therefore start splitting the read and write channels more clearly both in pyhomematic, but also in the consuming libraries like the homeassistant core component. E.g., by specifying the Sensornodes more often in pyhomematic and stopping to use Writenodes for event subscriptions in (e.g.) homeassistant core component

Any thoughts? I'm glad to help, but would wait for some guidance regarding the way forward from the experts

**Comment by danielperna84** [comment] 2020-12-18 20:09
@rbloehm 

I'm actually at a point where I think it might make more sense to completly re-do the HomeMatic integration.

What I have in mind so far:  
pyhomematic (or an alternative project to have a clear separation) should only act as a communication interface. A little bit like MQTT. There are a ton of device categories with MQTT support available in Home Assistant, and the logic is implemented in Home Assistant, not the MQTT broker.

To make things a bit easier, the new pyhomematic should also read and store all the paramsets of all detected devices. Essentially a cache (autobuilt on first connection, then refreshed on demand). By using this cache, the library could tell Home Assistant: "the parameter `STATE` is boolean and read-only" (which would be a binary sensor), "the parameter `STATE` is boolean and read-write" (which would be a switch), __OR__ do it differently if you have a more specific device-dependent implementation in the code.

Eventually my goal with this approch would be, that practically all devices will be supported in at least some simple form, and only complex devices like thermostats will be handled differently. And as said before, __not__ in the library, but in the consumer of the library. Only because pyhomematic initially happened to be build for Home Assistant doesn't mean the application-specific stuff has to be done in the library in my opinion. The result is a split-brain situation where problems could be either inside pyhomematic or in Home Assistant. And I heavily vote for keeping things separate. On top of that, there wouldn't be the requirement to always first update pyhomematic with support for a new device, and then update Home Assistant with the new pyhomematic version and possibly some device-specifiv stuff (like new classes) which sometimes is needed as well.

This new library then could be used in a custom Component while it's being developed. Along with a GUI to setup in Home Assistant. And when it reaches a stable form, it could replace the existing integration.

I would also set the entities to be named af if the `resolvenames` option is turned off. This will result in stable and uniqe entity IDs. The friendly-names then can be applied as the customizable friendly names. The way it is now is mainly driven by the way Home Assistant was years ago when the HomeMatic integration was first introduced. Much has changed since then, so things can be done differently now.

That being said, I'm aware that the HA-Devs want to keep out device-specific stuff as much as possible. So maybe there could be an additional library which does device-specifiy stuff. But I think it makes more sense to do logic within Home Assistant. The way it is now there are tons of callbacks registered to handle the events. It would be way more efficient if Home Assistant would just have one listener for the events, which passes the state changes to the correct entity. The entity logic would then know how to make use of the new value. In case of the blind actuators for example the entity-code would check the device-type (read-write on one channel or on different channels) and update the entity accordingly.

Obviously this would take a lot of work on the Home Assistant side. Simplifying pyhomematic to just do the messaging could be done fairly easy I guess. I actually already started doing that (the simplified pyhomematic) a while ago, but didn't find the time to finish it yet. Maybe during the holidays.

What do you think?

Mentioning @pvizeli to let him know about my thoughts on this.

**Comment by sVnsation** [comment] 2021-06-15 15:20
As this issue is open for more then 2 years now, I want to give some other desperate people some hints how to fix this the "ugly way". Beware of this issue before continuing: https://github.com/home-assistant/core/pull/44620#issuecomment-752181772

1. Download the current folder core/homeassistant/components/homematic/ folder for your installed core version.
e.g. https://github.com/home-assistant/core/tree/2021.6.4/homeassistant/components/homematic
(can be downloaded easily with https://download-directory.github.io/)
2. Create a folder config/custom_components/homematic on your home assistant machine
3. Copy content from downloaded folder from step 1 to folder from step 2
4. Replace this function in homeassistant/components/homematic/entity.py. 
Source: https://github.com/home-assistant/core/pull/44620
```
    def _subscribe_homematic_events(self):
        """Subscribe all required events to handle job."""
        # Ordered list of nodes to determine priority when subscribing to
        # events. Only one channel per parameter should be subscribed to
        # to avoid jumping values.
        # E.g., if a sensor node is given, that one should be used.
        # Highest priority is on the bottom
        node_priority = [
            self._hmdevice.ACTIONNODE,
            self._hmdevice.EVENTNODE,
            self._hmdevice.WRITENODE,
            self._hmdevice.ATTRIBUTENODE,
            self._hmdevice.BINARYNODE,
            self._hmdevice.SENSORNODE,
        ]

        def _channel_list_to_single_channel(channel_list):
            if len(channel_list) == 1:
                return channel_list[0]
            return self._channel

        channel_dict = {
            node: _channel_list_to_single_channel(channels)
            for metadata in node_priority
            for node, channels in metadata.items()
            if node in self._data  # Data is needed for this instance
        }

        for node, channel in channel_dict.items():
            # Remember the channel for this attribute to ignore invalid events later
            self._channel_map.add(f"{node}:{channel!s}")
        _LOGGER.debug("Channel map for %s: %s", self._address, str(self._channel_map))

        # Set callbacks
        self._hmdevice.setEventCallback(callback=self._hm_event_callback, bequeath=True)
```
5. insert version to config/custom_components/homematic/manifest.json 
as this a custom integration now and no longer a core integration
https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by alexanderlink** [comment] 2021-06-18 14:56
> As this issue is open for more then 2 years now, I want to give some other desperate people some hints how to fix this the "ugly way".

@sVnsation Works like a charm. Thanks a lot.
Now I can remove my other "ugly hacks" since this one is much better (so far).

**Comment by djm193** [comment] 2021-07-12 11:50
Hello Guys, thx for the "solution" however I cannot locate core/homeassistant/components/homematic/ folder. I integrated homematic just in the configuration.yaml with a few lines of code. 
What do I have to do? 
thx in advance!

**Comment by chises** [comment] 2021-09-24 08:53
Thank you @sVnsation for this solution. I implemented this on Home Assistant core-2021.9.7 supervisor-2021.09.1 with Raspberrymatic CCU as Docker container.
If i change the position within the homematic CCU the value is correct in Home Assistant. If i use the Home Assistant to change the position i have the "old" behavior: 0 or 100 only. Any idea/hint?

**Comment by sVnsation** [comment] 2021-09-24 09:07
@chises Whats your version downloaded in step 1? The example link leads to 2021.6.4.

**Comment by chises** [comment] 2021-09-24 09:17
i used 2021.9.7 with the following link:
https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fcore%2Ftree%2F2021.9.7%2Fhomeassistant%2Fcomponents%2Fhomematic

**Comment by sVnsation** [comment] 2021-09-24 09:54
Currently i'm on the failry old piVCCU version 3.47.15
But any time soon in the next weeks i also plan to migrate to the [rasperrymatic addon](https://github.com/jens-maus/RaspberryMatic/wiki/Installation-HomeAssistant) inside HA and HB-RF-USB.
I will report back if the solution still works.

In the mean time enable logging in the configuration.yaml:
```
logger:
  default: info
  logs:
    homeassistant.core: debug
    homeassistant.components.mqtt: debug
```

Look for the entries "Channel map for..." and post the log.

**Comment by chises** [comment] 2021-09-24 10:18
I am sorry, but the whole log file does not contain something like "channel map".
If i move with homematic i see multiple of these if different level and homeassistant value is correct:
`2021-09-24 12:11:48 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.37; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.37, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.560808+02:00>, new_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.566820+02:00>>
2021-09-24 12:11:48 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:48.564168+02:00>, new_state=<state cover.00115a499971c6=open; current_position=38, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.38, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:48.908912+02:00>>
2021-09-24 12:11:48 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.566820+02:00>, new_state=<state sensor.00115a499971c6_level=0.38; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.38, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.911634+02:00>>
2021-09-24 12:11:48 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=open; current_position=38, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.38, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:48.908912+02:00>, new_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:48.914304+02:00>>
2021-09-24 12:11:48 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.38; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.38, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.911634+02:00>, new_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.917106+02:00>>
2021-09-24 12:11:50 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:48.914304+02:00>, new_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.565889+02:00>>
2021-09-24 12:11:50 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:48.917106+02:00>, new_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.567576+02:00>>`

If i use the homeassistant to move i see almost the same: 
```
2021-09-24 12:15:11 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.908055+02:00>, new_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-87, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.908055+02:00>>
2021-09-24 12:15:11 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-83, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.908357+02:00>, new_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-87, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.908357+02:00>>
2021-09-24 12:15:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=cover, service=stop_cover, service_data=entity_id=cover.00115a499971c6>
2021-09-24 12:15:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-87, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.908055+02:00>, new_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.908055+02:00>>
2021-09-24 12:15:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-87, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.908357+02:00>, new_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.908357+02:00>>
2021-09-24 12:15:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=open; current_position=50, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.5, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:11:50.908055+02:00>, new_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:15:13.885265+02:00>>
2021-09-24 12:15:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.5; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.5, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:11:50.908357+02:00>, new_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:15:13.885549+02:00>>
2021-09-24 12:15:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:15:13.885265+02:00>, new_state=<state cover.00115a499971c6=open; current_position=31, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.31, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:15:21.285003+02:00>>
2021-09-24 12:15:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:15:13.885549+02:00>, new_state=<state sensor.00115a499971c6_level=0.31; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.31, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:15:21.285280+02:00>>
2021-09-24 12:15:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=cover.00115a499971c6, old_state=<state cover.00115a499971c6=open; current_position=31, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.31, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:15:21.285003+02:00>, new_state=<state cover.00115a499971c6=closed; current_position=0, id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen, supported_features=15 @ 2021-09-24T12:15:21.290122+02:00>>
2021-09-24 12:15:21 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.00115a499971c6_level, old_state=<state sensor.00115a499971c6_level=0.31; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.31, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:15:21.285280+02:00>, new_state=<state sensor.00115a499971c6_level=0.0; id=00115A499971C6, interface=HMIP, rssi_peer=-91, level=0.0, friendly_name=Bad Rollladen LEVEL @ 2021-09-24T12:15:21.290446+02:00>>```

**Comment by sVnsation** [comment] 2021-09-24 10:24
If the log file does not contain something like "channel map", then the custom_component isn't loaded.
The log should start with something like
`2021-09-22 18:38:02 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by sVnsation** [comment] 2021-09-24 17:35
@lud-hu @basekk @djm193 @chises 
Please vote for this Pullrequest https://github.com/home-assistant/core/pull/56619 to get this finally fixed.

**Comment by chises** [comment] 2021-09-25 06:15
> If the log file does not contain something like "channel map", then the custom_component isn't loaded.
> The log should start with something like
> `2021-09-22 18:38:02 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration homematic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

Found m issue, missed a "," in my manifest. I am sorry, everything is working!

**Comment by baron123** [comment] 2021-12-11 17:21
for me the problem solved with auto calibration on device parameter in ccu3

**Comment by danielperna84** [comment] 2023-09-10 16:30
Blind-devices are working properly with the [new integration](https://github.com/danielperna84/custom_homematic), therefore closing this issue.

**Closed by danielperna84** 2023-09-10 16:30 UTC
Labels: help wanted
