### ISSUE TITLE
HM-ES-TX-WM with ES-IEC -> Unknown Parameter

### ISSUE THREAD

**Issue by chriskroees** [danielperna84/pyhomematic#374] opened 2021-01-25 14:35 UTC
**Home Assistant version (if applicable):**
2021.1.5

**Describe the bug**
I am using an HM-ES-TX-WM with ES-IEC. The devices are shown in Home Assistant, but not the values:

Log Warnings:
Logger: pyhomematic.devicetypes.generic
Source: /usr/local/lib/python3.8/site-packages/pyhomematic/devicetypes/generic.py:212 
First occurred: 8:38:48 (22 occurrences) 
Last logged: 8:39:14

HMGeneric.getValue: RSSI_PEER on 0014D709AEF770:0 Exception: <Fault -5: 'Unknown Parameter value for value key: RSSI_PEER'>
HMGeneric.getValue: GAS_ENERGY_COUNTER on PEQ0544318:1 Exception: <Fault -5: 'Unknown parameter'>
HMGeneric.getValue: GAS_POWER on PEQ0544318:1 Exception: <Fault -5: 'Unknown parameter'>
HMGeneric.getValue: ENERGY_COUNTER on PEQ0544318:1 Exception: <Fault -5: 'Unknown parameter'>
HMGeneric.getValue: POWER on PEQ0544318:1 Exception: <Fault -5: 'Unknown parameter'>

**Expected behavior**
Values in the sensors from my CCU.

**Screenshots**
![image](https://user-images.githubusercontent.com/26657301/105719367-803de980-5f22-11eb-88e0-12ceb1eef822.png)
![image](https://user-images.githubusercontent.com/26657301/105719593-c004d100-5f22-11eb-8cae-69110bcfb8ee.png)

Thanks for your help!

**Comment by danielperna84** [comment] 2021-01-25 21:32
Hm, don't know what the problem is. I have the HM-ES-TX-WM with the LED-Sensor, and it's working without any issues. The warnings you are seeing regarding the missing parameters probably can be ignored. Depending on how the device is configured different paramters become active, and during startup of Home Assistant for __all__ of those the current values are fetched (because Home Assistant doesn't know which parameters are active). Which leads to the errors.

**Comment by chriskroees** [comment] 2021-01-28 14:24
Maybe you can see something in the debug log?

2021-01-28 14:42:30 DEBUG (SyncWorker_8) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = 'PEQ0544318:1', key = 'ENERGY_COUNTER'
2021-01-28 14:42:30 WARNING (SyncWorker_8) [pyhomematic.devicetypes.generic] HMGeneric.getValue: ENERGY_COUNTER on PEQ0544318:1 Exception: <Fault -5: 'Unknown parameter'>
2021-01-28 14:42:30 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.peq0544318_energy_counter, old_state=None, new_state=<state sensor.peq0544318_energy_counter=False; id=PEQ0544318, interface=rf, battery=High, rssi_peer=-73, rssi_device=-65535, unit_of_measurement=Wh, friendly_name=eg_har_stromzaehler ENERGY_COUNTER @ 2021-01-28T14:42:30.868076+01:00>>
2021-01-28 14:42:30 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2915931160] Sending {"id": 2, "type": "event", "event": {"event_type": "state_changed", "data": {"entity_id": "sensor.peq0544318_energy_counter", "old_state": null, "new_state": {"entity_id": "sensor.peq0544318_energy_counter", "state": "False", "attributes": {"id": "PEQ0544318", "interface": "rf", "battery": "High", "rssi_peer": -73, "rssi_device": -65535, "unit_of_measurement": "Wh", "friendly_name": "eg_har_stromzaehler ENERGY_COUNTER"}, "last_changed": "2021-01-28T13:42:30.868076+00:00", "last_updated": "2021-01-28T13:42:30.868076+00:00", "context": {"id": "437243e43e90a5e8fb8752a5e82a55c5", "parent_id": null, "user_id": null}}}, "origin": "LOCAL", "time_fired": "2021-01-28T13:42:30.868076+00:00", "context": {"id": "437243e43e90a5e8fb8752a5e82a55c5", "parent_id": null, "user_id": null}}}
2021-01-28 14:42:30 DEBUG (SyncWorker_0) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = 'PEQ0544318:0', key = 'LOWBAT'
2021-01-28 14:42:30 DEBUG (SyncWorker_0) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = 'PEQ0544318:0', key = 'RSSI_PEER'
2021-01-28 14:42:30 DEBUG (SyncWorker_0) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = 'PEQ0544318:0', key = 'RSSI_DEVICE'
2021-01-28 14:42:30 DEBUG (SyncWorker_0) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = 'PEQ0544318:1', key = 'POWER'

This is my configuration on the ccu:

![image](https://user-images.githubusercontent.com/26657301/106151670-e2922680-617c-11eb-85fd-720e23661ba8.png)

Any ideas how to proceed with this problem?

**Comment by simonszu** [comment] 2021-02-10 17:30
I have the same issue. I had my HM-ES-TX-WM with an ES-FER sensor until recently when my power provider changed the meter. The device was working fine with this configuration. Now i upgraded the TX-WM's firmware to have compatibility with the ES-IEC sensor. The homematic stuff works as expected, i see the values of the readings in the CCU, but regarding the connection to Home Assistant i have the same issue like @chriskroees. 

The interesting part is: Home Assistant seems to be able to retreive data from the sensor, but it is then not properly handled internally. I see these lines in the log:

```
2021-02-10 18:24:05 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0704600:1, interface_id=homeassistant-default, key=IEC_ENERGY_COUNTER, value=3183.7082
2021-02-10 18:24:05 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0704600:1, interface_id=homeassistant-default, key=IEC_POWER, value=626.0
2021-02-10 18:24:06 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0704600:2, interface_id=homeassistant-default, key=IEC_ENERGY_COUNTER, value=0.626
2021-02-10 18:24:06 INFO (Thread-3) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0704600:2, interface_id=homeassistant-default, key=IEC_POWER, value=626.0
```
The values are correct. But the keys which are visible in Home Assistant are LOWBAT, ENERGY_COUNTER and POWER - without the IEC prefix. These keys do not have any value.

**Comment by simonszu** [comment] 2021-02-12 10:19
From what i see in the code, i think it would be sufficient if the channels IEC_POWER and IEC_ENERGY_COUNTER in this method block: https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/sensors.py#L202

However, i am not an expert python programmer, so i can only provide an untestet pull request based on my assumptions. and since the actual code writing without the testing is trivial, i would like to pass the ball back to @danielperna84, hoping you can implement this quickly :)

**Comment by ASealion** [comment] 2021-02-27 14:18
I've just installed the hm-es-tx-wm with the iec sensor and have the same problem.

I think EQ3 changed something between the firmware 1 and 2 of the sensor since they are not compatible.
You must use a version 2 if you have a ES-IEC and a version 1.xx for all other sensors.

**Comment by ASealion** [comment] 2021-03-01 20:09
If just read the device desrciption and parameters from the ccu, maybe @danielperna84 could see if he could add this a a "second" HM-ES-TX-WM device.

https://gist.github.com/ASealion/0cb7df2aa1fa24b0237376a3fdf6597f

**Comment by climblinne** [comment] 2021-05-16 09:24
I added the support for ES-IEC (needs firmware 2.5).
![image](https://user-images.githubusercontent.com/9393574/118392258-faf95480-b638-11eb-923c-c56c2fdbfabf.png)
Dependend of your power meter you can also use two channels of energy counter (e.g IN & OUT) and two channel of power.

**Comment by danielperna84** [comment] 2021-06-06 15:52
PR for Home Assistant is here: https://github.com/home-assistant/core/pull/51551

And it's referencing your PR, so this should be addressed shortly. Closing this issue.

**Closed by danielperna84** 2021-06-06 15:52 UTC
