### ISSUE TITLE
System Variables

### ISSUE THREAD

**Issue by freeki** [danielperna84/pyhomematic#40] opened 2016-09-27 07:07 UTC
Hi and hello,

i would like to use this platform to ask, whether there is an option already existing, or any plans, to be able to read/write systemvariables from the CCU yet.

This is at the moment the only major topic missing within pyHomematic in my opinion.

Thanks for any feedback!

**Comment by danielperna84** [comment] 2016-09-27 18:14
We already support that. But it admittedly may be limited in functionality.
I assume you are coming from Home Assistant. In the homematic-configuration, you can set ```variables: True``` to enable this.
This will display the variables (bool and float, nothing else for now), as entities within HA. The values are polled once a minute. Sadly the CCU doesen't send events when variables change (Homegear does though), so polling is our only option. Setting variables should work immediately.

Generally, we could support more than bool and float und evend handle live updates with Homegear. But we are limiting ourselves to what the CCU can handle, which sadly is only setting floats and bools and not notifying about changes.

**Comment by freeki** [comment] 2016-09-28 14:35
Thank you very much for getting back to me on this.
I didn't know that there was an option already.
i will try that out.

I just wonder: will the polling interval of 1 minute effect the CCU performance badly?

There is a tool, ioBroker, that get triggered right after systemvariables change... any idea, why iobroker get's aware of those changes directly?

Thanks again!!

And yes: i am coming from HA :)

**Comment by danielperna84** [comment] 2016-09-28 20:31
Could you provide the log of the startup of HA? Until now nobody really mady use of the variables, so we couldn't verify everything is working properly. Although in our tests we saw all the variables as entities. They should be grouped and listed within the Homematic-card. To have access to the variables you also have to configure a valid user that has sufficient privileges.

Since we haven't tested bigger setups that make use of variables I can't tell (regarding performance). Would be nice if you could give feedback. But I assume the load should be fairly low. It's one request each minute, and I hope the CCU ist programmed to handle such requests efficiently.

I don't know about ioBroker and how it's done there. I know that Homegear sends event-messages. pvizeli has a CCU, and from his oberservations the CCU doesn't seem to send such events. In this case it would be interesting to see how ioBroker is doing that. In the beginning when I was implementing it with Homegear I planned to update the variable-values directly. But since the CCU didn't support it that way we switched to polling. Which I don't like, but it's still better than nothing.
If you want you can investigate about this. Maybe we'll find a solution that doesn't rely on polling.

**Comment by pvizeli** [comment] 2016-09-28 20:44
Variable don't be updated from CCU:
https://github.com/openhab/openhab/wiki/Homematic-Binding
There is a caption who explane hack for provide a CCU for a update but that is not user friendly. All other is polling.

**Comment by freeki** [comment] 2016-09-28 21:14
I will share those details later, but as far as I could see there is no remark that something is not working....

BTW.. this is the module iobroker is using to keep in sync with the ccu variables.... it works perfect :)

https://github.com/ioBroker/ioBroker.hm-rega

**Comment by freeki** [comment] 2016-09-29 13:27
Thanks for your tip so far.... i have it up an running.
But there seems to be some kind of bug:

When setting values via Home Assistant:

Setting floats works without problems
Setting bools to `true` works too
Setting bools to `false` doesnt work at all. It just stays `true` all the time.

Home Assistant is loggin no errors here.
Is there any place i could search for some logs??

**Comment by danielperna84** [comment] 2016-09-29 13:39
Ok, we'll have to investigate that. To get more logoutput, you can change the configuration in HA like this:
```yaml
logs:
  homeassistant.components.homematic: debug
  pyhomematic: debug
```

**Comment by freeki** [comment] 2016-09-29 13:48
strange enough variables just stopped starting up:

Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/bootstrap.py", line 102, in _setup_component
    result = component.setup(hass, config)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/homematic.py", line 234, in setup
    entities.append(HMHub(hm_var_store, use_variables))
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/homematic.py", line 509, in __init__
    self.update()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/homematic.py", line 539, in update
    self._update_variables_state()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/homematic.py", line 558, in _update_variables_state
    self._store.get(key).hm_update(value)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/homematic.py", line 593, in hm_update
    self.update_ha_state()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 147, in update_ha_state
    raise RuntimeError("Attribute hass is None for {}".format(self))
RuntimeError: Attribute hass is None for <Entity svEnergyCounterOldVal_2473: 339185.299805>

**Comment by danielperna84** [comment] 2016-09-29 14:49
First of all I see an incorrect string in our code. The "deleting" is not correct. But that has no influence, that's just the message. The other messages show that the correct RPC-method is being called.
In general it's looking good. Although I don't know if the returncode 1 (the one at the deleting-message) is a bad thing (that's specific to the CCU, which I don't have). Which results do you get when setting a float, or in general if it's successful?

If you're fine fiddling with the code, you could add:
```python
LOG.debug("RPCFunctions.jsonRpcPost: Payload: %s" % str(payload))
```
to line 216 of _hm.py. This would log all the data that is being sent to the CCU. This will however include the login-credentials. So if you try that, remove that data before posting the log.

**Comment by freeki** [comment] 2016-09-29 15:15
for setting the floats it looks the same:

DEBUG:pyhomematic._hm:ServerThread.setSystemVariable: Setting System variable via JSON-RPC
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: Method: Session.login
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: API-Endpoint: http://192.168.1.25/api/homematic.cgi
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: Method: SysVar.setFloat
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: API-Endpoint: http://192.168.1.25/api/homematic.cgi
DEBUG:pyhomematic._hm:ServerThread.setSystemVariable: Result while deleting: 1.0
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: Method: Session.logout
DEBUG:pyhomematic._hm:RPCFunctions.jsonRpcPost: API-Endpoint: http://192.168.1.25/api/homematic.cgi

**Comment by freeki** [comment] 2016-09-29 15:18
now what i just saw:

when setting a float
DEBUG:pyhomematic._hm:ServerThread.setSystemVariable: Result while deleting: `1` reflectrs the state of the float
1=1.0, 2=2.0 etc....

when setting the bool it is always `1`
shouldnt it set `0` for `false` ???

**Comment by danielperna84** [comment] 2016-09-29 15:53
That could help finding the issue. I assume the problem is in the HA implementation, which somehow has trouble dealing with the ```False``` value. I'll have a closer look at that later.

**Comment by danielperna84** [comment] 2016-09-29 21:02
How do you set variables?
If you do it via the HA-UI you have the possibility to it via http://123.123.123.123:8123/dev-event
There you can call the service ```homematic.set_value``` with the data ```{"entity_id": "homematic.testvar", "state": 0}```. You can't use ```True``` or ```False``` instead without using quotation. Quotation though casts the value to a string, an ```bool("False")``` actually is ```True```.
Unfortunately my productive HA is still at 26.x, and there it doesn't seem to work at all. Variables were in a very early stage back then. But maybe the information above can solve the issue.

**Comment by freeki** [comment] 2016-09-29 21:57
i am doing it exactly that way.

I tried everything (just now a gain to verify)

-{"entity_id":"homematic.vmware","value":"false"}
-{"entity_id":"homematic.vmware","value":false}
-{"entity_id":"homematic.vmware","value":"0"}
-{"entity_id":"homematic.vmware","value":0}

none of this works.
but only for `false`

Anything else works flawless.
my FW is 2.19.9 btw.

**Comment by danielperna84** [comment] 2016-09-29 22:17
I have checked by using pyhomematic manually from shell and it worked. So it seems to be an issue within HA.
The way I tested:
```python
from pyhomematic import HMConnection
p = HMConnection(interface_id="test", local="192.168.1.118", localport=7080, remote="192.168.1.21", remoteport=2001, autostart=True)
p.getSystemVariable("hmtest")
# True
p.setSystemVariable("hmtest", False)
p.getSystemVariable("hmtest")
# False
p.stop()
```
pyhomematic seems to do it's job like it should.
I'm not sure how HA handles all this with the services. Maybe @pvizeli has an idea. But the fix has to be done in HA.

**Comment by freeki** [comment] 2016-10-02 06:27
Will your change be part of 1.1.15?

Say, when working with variables, is there a way to just show some selected variables?
Right know a lot of hidden ' intern variables are also shown. 
Like internal power counters .....

**Comment by pvizeli** [comment] 2016-10-02 07:50
I check that and fix it in hm_next branch. But the cv.boolean is needed to parse it in right way. I think it need to conert lowercase the value

**Comment by pvizeli** [comment] 2016-10-02 09:14
You can make a variable unvisible per customize see on documentation on HA. The phisolophie from HA is that all possible things are present and can modify by customize

**Comment by freeki** [comment] 2016-10-02 11:12
That's right. 
But my problem is that hidden variables still get logged in logbook for example. Now with this Energie counters running and spamming the logbook, db file sizes are just getting unnecessary big.  

Well.... I will try something out.

**Comment by pvizeli** [comment] 2016-10-03 09:21
https://home-assistant.io/components/logbook/

**Comment by pvizeli** [comment] 2016-10-03 20:39
I have test it and it work with 0.30dev. So I think in the next version is it fix.
`{ "entity_id": "homematic.test", "value": false }`

**Comment by danielperna84** [comment] 2016-10-03 21:00
For me it also works using 0.30dev together with Homegear. So this seems to have been an issue within HA and not our usage of cv.boolean.

@freeki 
Feel free to close the issue if you can confirm this is working.

**Closed** 2016-10-12 20:46 UTC
Labels: wontfix
