### ISSUE TITLE
support for HM-Sec- Key

### ISSUE THREAD

**Issue by trilu2000** [danielperna84/pyhomematic#45] opened 2016-11-23 16:50 UTC
Hi Daniel,
thanks for your work to integrate Homegear.
I've got a HM-Sec-Key device, which is recognized in home-assistant but switch functions produces an error:

`16-11-23 17:43:17 homeassistant.core: Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 1050, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/__init__.py", line 92, in async_handle_switch_service
    yield from switch.async_turn_off()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity.py", line 356, in async_turn_off
    None, ft.partial(self.turn_off, **kwargs))
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/homematic.py", line 59, in turn_off
    self._hmdevice.off(self._channel)
AttributeError: 'KeyMatic' object has no attribute 'off'  `

There is no On or Off state for the HM-Sec-Key. 
VALUES of channel 1 are the following:
`{ "DIRECTION": 3,
  "ERROR": 0,
  "INHIBIT": false,
  "STATE": true,
  "STATE_UNCERTAIN": true }
`

This are the possible values:
`{
  "DIRECTION": {
    "DEFAULT": 0,
    "FLAGS": 3,
    "ID": "DIRECTION",
    "MAX": 3,
    "MIN": 0,
    "OPERATIONS": 5,
    "TAB_ORDER": 0,
    "TYPE": "ENUM",
    "UNIT": "",
    "VALUE_LIST": [
      "NONE",
      "UP",
      "DOWN",
      "UNDEFINED"
    ]
  },
  "ERROR": {
    "CONTROL": "NONE",
    "DEFAULT": 0,
    "FLAGS": 9,
    "ID": "ERROR",
    "MAX": 2,
    "MIN": 0,
    "OPERATIONS": 5,
    "TAB_ORDER": 1,
    "TYPE": "ENUM",
    "UNIT": "",
    "VALUE_LIST": [
      "NO_ERROR",
      "CLUTCH_FAILURE",
      "MOTOR_ABORTED"
    ]
  },
  "INHIBIT": {
    "CONTROL": "NONE",
    "FLAGS": 1,
    "ID": "INHIBIT",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 7,
    "TAB_ORDER": 2,
    "TYPE": "BOOL",
    "UNIT": ""
  },
  "INSTALL_TEST": {
    "FLAGS": 3,
    "ID": "INSTALL_TEST",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 2,
    "TAB_ORDER": 3,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "OPEN": {
    "CONTROL": "LOCK.OPEN",
    "FLAGS": 1,
    "ID": "OPEN",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 2,
    "TAB_ORDER": 4,
    "TYPE": "ACTION",
    "UNIT": ""
  },
  "RELOCK_DELAY": {
    "CONTROL": "NONE",
    "DEFAULT": 111600,
    "FLAGS": 1,
    "ID": "RELOCK_DELAY",
    "MAX": 65535,
    "MIN": 0,
    "OPERATIONS": 2,
    "SPECIAL": [
      {
        "ID": "NOT_USED",
        "VALUE": 111600
      }
    ],
    "TAB_ORDER": 5,
    "TYPE": "FLOAT",
    "UNIT": "s"
  },
  "STATE": {
    "CONTROL": "LOCK.STATE",
    "FLAGS": 1,
    "ID": "STATE",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 7,
    "TAB_ORDER": 6,
    "TYPE": "BOOL",
    "UNIT": ""
  },
  "STATE_UNCERTAIN": {
    "CONTROL": "LOCK.UNCERTAIN",
    "DEFAULT": true,
    "FLAGS": 1,
    "ID": "STATE_UNCERTAIN",
    "MAX": true,
    "MIN": false,
    "OPERATIONS": 5,
    "TAB_ORDER": 7,
    "TYPE": "BOOL",
    "UNIT": ""
  }
}`

Is it possible to implement this device?

Best regards
Horst

**Comment by danielperna84** [comment] 2016-11-24 14:38
Hi,

yes somehow it will be possible. But without a device to test it it's not that easy. We've done the implementation by looking at the documentation in [hm_devices_Endkunden.pdf](http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf). There it's saying, that the device should be able to behave like a switch-actor. Although I saw just now, that the KeyMatic-object is not inheriting from the Switch-class.

Anyhow, the KeyMatic-object provides an Action-Node, which has to be called with open. So instead of having a switch in the HASS UI, the device should be controlled with a service-call. So something like this:
```yaml
action:
  service: homematic.virtualkey
  data:
    address: MEQ1324657
    channel: 1
    param: OPEN
```
Since we couldn't test that we don't know what that actually does. I would assume this would unlock the device, which closes after some amount of time. At least that's what I thought the device works like.
Indeed it would also make sense to make this device work like a regular switch since it should be capable of doing that.

So, could you please clarify what the device can to, and how that relates to the paramters the documentation above mentions?

**Comment by trilu2000** [comment] 2016-11-26 10:59
I can imagine that it is not easy to implement without having the device, but thanks for trying...
In principle the Key-Sec has to switching flags 

1. state - setting false locks the door 'verriegelt'
setting true - unlocks the door 'entriegelt'

2. open - setting true opens the door 'wirkliches öffnen, wie Türklinke drücken'

Then there is a thrird flag which is interesting, STATE_UNCERTAIN
means - the device is not sure if the door was opened from outside by a key

If there is anything more you need to know please let me know...

**Comment by danielperna84** [comment] 2016-11-26 11:10
@pvizeli has pushed a commit, which should enable the usage of the device as a switch. That will be included in the next HASS release, which will reference the new pyhomematic version.
If you want you can try it out and confirm that it's working by manually applying the changes from commit ab7ffd3747f81e3b462b0a1226e1afeca7992587 to the pyhomematic your HASS is using. How that's done depends on how you're running hass.

Have you tried my suggestion regarding the OPEN-action through usage of the homematic.virtualkey service? You can also do that through the HASS UI on the services-site (your-hass-url/dev-service).
The payload then should look something like:
```json
{
  "address": "LEQ1234657",
  "channel": 1,
  "param": "OPEN"
}
```

This should already be working.

Regarding the STATE_UNCERTAIN it probably would make sense to generate an additional sensor-entity in HASS, which could then be tracked using automations. Do you agree on that being a useful way of using the data?

**Comment by trilu2000** [comment] 2016-11-26 11:44
tried via the service console - but unfortunately not working
16-11-26 12:40:35 homeassistant.components.homematic: 1 is not a channel in hm device KEQ0856675
tried also with the state flag
16-11-26 12:42:11 homeassistant.components.homematic: STATE not datapoint in hm device KEQ0856675
Is there any options where i can see which data home assistant knows abot my HM devices?

**Comment by danielperna84** [comment] 2016-11-26 19:42
I have added another fix to the actors.py file (added the ELEMENT-property). Could you please try again? That could actually make the entity work as a switch and open the lock with the service.

The data HASS knows about your device can be seen on the entities-page in the HASS-UI. It should be one of the switch-devices.

**Comment by trilu2000** [comment] 2016-11-27 15:02
patched the actor.py - if i click now the device in hass gui i get following error in the log:
`16-11-27 15:56:11 homeassistant.core: Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 1050, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/__init__.py", line 92, in async_handle_switch_service
    yield from switch.async_turn_off()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity.py", line 356, in async_turn_off
    None, ft.partial(self.turn_off, **kwargs))
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/homematic.py", line 59, in turn_off
    self._hmdevice.off(self._channel)
AttributeError: 'KeyMatic' object has no attribute 'off'
`

tried also the patch in homematic.py - by sending the action as virtual key i get
`16-11-27 15:59:23 pyhomematic.devicetypes.generic: HMGeneric.setValue: Exception: <Fault -5: 'Parameter of type action cannot be set to "false".'>
`

If i look to the entities page in HASS it seems there is no channel definition of the device available:
{
  "ID": "KEQ0856675",
  "RSSI": -74,
  "friendly_name": "EG_FLR_Motorschloss"
}

**Comment by danielperna84** [comment] 2016-11-27 15:25
1. How did you patch the actors.py? My change with the ELEMENT-property wasn't relevant. But making the KeyMatic class inherit from GenericSwitch (```class KeyMatic(GenericSwitch)```) should have done the trick for locking and unlocking the device through the UI.

2. How did the payload look like?

The channels aren't listed in the entity-data, since there can be multiple channels, and they usually is no need to show them.

**Comment by danielperna84** [comment] 2016-11-27 15:34
And one more thing that comes to my mind:
try changing ```1``` to ```True``` in [https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic.py](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic.py#L473)
Maybe that get's the OPEN-action to work.

**Comment by trilu2000** [comment] 2016-11-27 15:35
i patched it in the installed file on my raspberry
vi /usr/local/lib/python3.4/dist-packages/homeassistant/components/homematic.py
and restarted the home-assistant-service

16-11-27 16:33:44 pyhomematic.devicetypes.generic: HMGeneric.setValue: key = 'OPEN' value = '1'
16-11-27 16:33:44 pyhomematic.devicetypes.generic: HMGeneric.setValue: Exception: <Fault -5: 'Parameter of type action cannot be set to "false".'>

that is all i get within the log file while pyhomematic is on debug
Is there any way to get more information and debug with python?

**Comment by danielperna84** [comment] 2016-11-27 15:38
The patch I meant was meant for pyhomematic itself. So the actors.py on your system has to be in sync with [actors.py](https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/actors.py)

**Comment by trilu2000** [comment] 2016-11-27 15:47
> try changing 1 to True in https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic.py

That made the virtual key working! great

Should i reroll the patch on actors.py?

**Comment by danielperna84** [comment] 2016-11-27 15:50
Great!

Yes. I suggest to replace the whole file to make sure everything in there is up to date.

**Comment by trilu2000** [comment] 2016-11-27 15:58
ok, downloaded the whole file from git - but still the problem that pushing the button in HASS Gui is not working

`Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 1050, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/__init__.py", line 92, in async_handle_switch_service
    yield from switch.async_turn_off()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity.py", line 356, in async_turn_off
    None, ft.partial(self.turn_off, **kwargs))
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/homematic.py", line 59, in turn_off
    self._hmdevice.off(self._channel)
AttributeError: 'KeyMatic' object has no attribute 'off'
`

**Comment by danielperna84** [comment] 2016-11-27 16:07
Hhmm, doesn't make sense to me. Other switches are working. You can change the loglevel like this:
```yaml
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.homematic: debug
    pyhomematic: debug
```

Maybe that will provide some useful information.

**Comment by trilu2000** [comment] 2016-11-27 16:30
you are right, all my other stuff is working. please don't get me wrong, i appreciate your support and didn't want to blame...
added the missing line homeassistant.components.homematic to the logger but still the same output...

16-11-27 17:10:21 homeassistant.core: Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 1050, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/__init__.py", line 92, in async_handle_switch_service
    yield from switch.async_turn_off()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity.py", line 356, in async_turn_off
    None, ft.partial(self.turn_off, **kwargs))
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/homematic.py", line 59, in turn_off
    self._hmdevice.off(self._channel)
AttributeError: 'KeyMatic' object has no attribute 'off'


within the entities i see one difference from a normal switch device to the keymatic

switch.dg_msd_reserve	off	ID: KEQ1109986
RSSI: -60
Working: No
friendly_name: DG_MSD_Reserve

switch.eg_flr_motorschloss	on	ID: KEQ0856675
RSSI: -61
friendly_name: EG_FLR_Motorschloss

There is no Working flag listed

**Comment by danielperna84** [comment] 2016-11-27 16:39
That's because the KeyMatic does not have that parameter.

Since I'm running out of ideas, could you please try to use pyhomematic manually as seen in [example.py](https://github.com/danielperna84/pyhomematic/blob/master/example.py)?

Within the shell you should be able to do the following operations:
```python
pyhomematic.devices["KEQ0856675"].is_on()
pyhomematic.devices["KEQ0856675"].is_off()
pyhomematic.devices["KEQ0856675"].on()
pyhomematic.devices["KEQ0856675"].off()

# and do this so we can see what the object actually looks like
dir(pyhomematic.devices["KEQ0856675"])
```

**Comment by trilu2000** [comment] 2016-11-27 16:50
dir(pyhomematic.devices["KEQ0856675"])
['ACTIONNODE', 'ADDRESS', 'ATTRIBUTENODE', 'BINARYNODE', 'CHANNELS', 'ELEMENT', 'EVENTNODE', 'NAME', 'PARAMSETS', 'SENSORNODE', 'TYPE', 'UNREACH', 'WRITENODE', '_ACTIONNODE', '_ADDRESS', '_ATTRIBUTENODE', '_AVAILABLE_FIRMWARE', '_BINARYNODE', '_CHANNELS', '_CHILDREN', '_EVENTNODE', '_FAMILY', '_FIRMWARE', '_FLAGS', '_ID', '_INTERFACE', '_PARAMSETS', '_PARAMSET_DESCRIPTIONS', '_PARENT_TYPE', '_PHYSICAL_ADDRESS', '_RF_ADDRESS', '_ROAMING', '_RX_MODE', '_SENSORNODE', '_TYPE', '_UPDATABLE', '_VERSION', '_WRITENODE', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_eventcallbacks', '_getNodeData', '_hmchannels', '_name', '_paramsets', '_proxy', '_setNodeData', '_unreach', 'actionNodeData', 'event', 'getAttributeData', 'getBinaryData', 'getParamsetDescription', 'getSensorData', 'getValue', 'getWriteData', 'get_rssi', 'get_state', 'is_off', 'is_on', 'off', 'on', 'putParamset', 'setEventCallback', 'setValue', 'set_state', 'updateParamset', 'updateParamsets', 'writeNodeData']

Cool :-)
Played in the past with PERL and FHEM arround, but now i like python definately more

I can drive the HM-KEY-SEC with 
pyhomematic.devices["KEQ0856675"].on() 
pyhomematic.devices["KEQ0856675"].off()

**Comment by danielperna84** [comment] 2016-11-27 16:57
Yes, Python is quite nice. That's why I left FHEM behind and started with this library. ;-)

Ok, so now we know, that the object pyhomematic is generating generally is capable of doing everything like it should. For some reason though HASS doesn't see the on/off methods.

@pvizeli any idea why that happens?

**Comment by trilu2000** [comment] 2016-11-27 17:23
How flexible is your library? I am asking while i am developing an HM framework for Arduino. Target is to generate own devices. Additional i am creating xml device files for the ccu or homegear to let them know about the functionallity of the specific device. Currently i have the switch modul working, dimmer misses some configuration variables, next to come is a remote and sensor module.
As explained, the devices will have their own xml file while could be a mix of a switch with a remote and some sensor channels. The sensor channels can transmit values as degree celcius, or % humidity or watt or whatever.
Within FHEM their was no easy way of introducing new devices, while everything was hardcoded in some modules. Homegear is flexible enough to handle new devices on base of the xml file, is home-assistant, or your module flexible enough?

**Comment by danielperna84** [comment] 2016-11-27 17:39
We don't parse any XML. Device support has to be manually introduced, like you can see with the switches in actors.py. But you can mix different types quite easily and create new classes. So for example the class for the power-meter-switch inherits it's capabilities from the generic HMDevice class, but also some from one of the Switch classes, and somehow also of sensors.
So basically we're trying to rebuild what the XML-files are telling us with Python-Objects inheriting from one another.

The problem I see in your case is, that EQ3 probably will never add the XML files for the devices you build to the CCU. So they will only work with Homegear.

Personally I think it would make more sense to let them use the MQTT protocol. I'm pretty sure there are already quite a lot Arduino-projects doing just that. And with MQTT those devices work with HASS out of the box, and also pretty much any other application capable of speaking MQTT. As far as I know there's even somehow the possibility to talk MQTT with the CCU (Google hm2mqtt). Even Homegear supports MQTT.
So instead of limiting yourself to follow the specification of a vendor that's mostly active in the german speaking area, why not go global with a protocol that's spoken internationally?

**Comment by danielperna84** [comment] 2016-11-27 18:19
Regarding KeyMatic:
Turns out the switching may be fixed by some other change that's already up to be merged for the next HASS release. The Pull Request where all this happens is here: [4568](https://github.com/home-assistant/home-assistant/pull/4568)

**Comment by trilu2000** [comment] 2016-11-27 18:29
i like the idea of peering devices :-)
mqtt is a server based protocol, but with homematic you can communicate between certain devices.
Imagine, your server is down but your blind is out and it starts raining :-)

**Comment by danielperna84** [comment] 2016-11-27 21:04
Since I have never done device peering I can't say much about that. But I would stick to my opinion, that such a device should still be, additionally to enything else, capable of talking MQTT.  
Event though pyhomematic would be capable of supporting your devices, the classes for self-made devices shouldn't be in pyhomematic by default. Some sort of plug-in mechanism would be ok. But letting custom devices enter our code could lead other developers to also wanting to do that, and then we would have to decide which classes make it into the final release, and nobody except the owner could actually verify everything is working correctly.
So, yeah, I guess some sort of Plug-In functionality may make sense in that case.

**Comment by danielperna84** [comment] 2016-11-29 14:03
Closing this issue since the bug should be fixed now. It might be reasonable to convert the current type from a switch to a lock-type, which exposes open/close methods instead of on/off. But that's just cosmetic and should be part of another issue.

**Comment by danielperna84** [comment] 2017-04-27 19:42
Seems as if this issue wasn't fixed with the update: https://community.home-assistant.io/t/keymatic-with-homegear/16469

**Comment by tringler** [comment] 2017-04-28 18:31
As I mentioned in https://community.home-assistant.io/t/keymatic-with-homegear/16469/21 the script is not working for me:
```
#!/usr/bin/python3
import time
import sys
import logging
from pyhomematic import HMConnection

logging.basicConfig(level=logging.INFO)

def systemcallback(src, *args):
    print(src)
    for arg in args:
        print(arg)

try:
    pyhomematic = HMConnection(interface_id="myserver",
                               autostart=True,
                               systemcallback=systemcallback,
                               remotes={"rf":{
                                   "ip":"127.0.0.1",
                                   "port": 2001}})
except Exception:
    sys.exit(1)

sleepcounter = 0

def eventcallback(address, interface_id, key, value):
    print("CALLBACK: %s, %s, %s, %s" % (address, interface_id, key, value))

while not pyhomematic.devices and sleepcounter < 20:
    print("Waiting for devices")
    sleepcounter += 1
    time.sleep(1)
print(pyhomematic.devices)

pyhomematic.devices["FEQ00XXXXX"].setEventCallback(eventcallback)
time.sleep(10)

print(pyhomematic.devices["FEQ00XXXXX"].on())
print(pyhomematic.devices["FEQ00XXXXX"].is_on())

time.sleep(10)
print(pyhomematic.devices["FEQ00XXXXX"].off())
print(pyhomematic.devices["FEQ00XXXXX"].is_off())

pyhomematic.stop()

sys.exit(0)
```

I also tried `feq00XXXXX`

**Comment by tringler** [comment] 2017-04-28 18:33
Can you teach how can I get a list of device ids from pyhomematic?

**Comment by danielperna84** [comment] 2017-04-28 19:05
That's actually what the line with `print(pyhomematic.devices)` should already do. One of the first things you would see would be a large block with all the devices that were detected.

**Comment by tringler** [comment] 2017-04-28 19:17
That's my output:
```
INFO:pyhomematic._hm:Creating proxy rf. Connecting to http://127.0.0.1:2001
createDeviceObjects
INFO:pyhomematic._hm:Starting server at http://0.0.0.0:34635
INFO:pyhomematic._hm:Proxy initialized
{'rf': {}}
Traceback (most recent call last):
  File "example.py", line 35, in <module>
    pyhomematic.devices["FEQ00XXXXX"].setEventCallback(eventcallback)
KeyError: 'FEQ00XXXXX'
listDevices
myserver-rf
```

After that I got all the homegear debug messages.

**Comment by danielperna84** [comment] 2017-04-28 20:02
I think it will work better if you do it manually on the Python shell. Open the Python shell by entering `python3` on the commandline. From there, enter the following commands one after another:

```python
import logging
from pyhomematic import HMConnection
logging.basicConfig(level=logging.INFO)
pyhomematic = HMConnection(interface_id="myserver", autostart=True, remotes={"rf":{"ip":"127.0.0.1", "port": 2001}})
# Now wait a few seconds. You should see some output
print(pyhomematic.devices)
# Now you should see all the devices you have
```

**Comment by danielperna84** [comment] 2017-04-28 21:50
I've made another minor modification for KeyMatic in [actors.py](https://github.com/danielperna84/pyhomematic/blob/KeyMatic/pyhomematic/devicetypes/actors.py). If you replace the actors.py from HASS with this one AND perform the modification mentioned below, you should get two more sensors: ERROR (a numeric value) and STATE_UNCERTAIN (True if the lock doesn't know the actual state).
Needed chage in [homematic.py](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic.py#L59) from HASS:
Add `'KeyMatic'` to the `DISCOVER_SENSORS` and `DISCOVER_BINARY_SENSORS` lists.

**Comment by tringler** [comment] 2017-04-29 05:30
After applied your modification I restarted HASS and I was able to see the new sensors. Values were 0 for `sensor.feq00xxxxx_error` and off. for `binary_sensor.feq00xxxxx_state_uncertain`. After I reproduced the error `sensor.feq00xxxxx_error` changed to value `2`. The attribute `sabotage` also changed to value `2`. `binary_sensor.feq00xxxxx_state_uncertain` is still `off`.

**Comment by tringler** [comment] 2017-04-29 07:38
```
import logging
from pyhomematic import HMConnection
logging.basicConfig(level=logging.INFO)
pyhomematic = HMConnection(interface_id="myserver", autostart=True, remotes={"rf":{"ip":"127.0.0.1", "port": 2001}})
# Now wait a few seconds. You should see some output
print(pyhomematic.devices)
# Now you should see all the devices you have
pyhomematic.stop()
```

is working via python shell and I get following output:
`'FEQ00XXXXXX': <pyhomematic.devicetypes.actors.KeyMatic object at 0x759a7090>`

If I try to execute `pyhomematic.devices['FEQ00XXXXX'].setEventCallback(eventcallback)` I get the known error: `KeyError: 'FEQ00XXXXX'`

I also tried these syntax without any success:
`pyhomematic.devices[FEQ00XXXXX].setEventCallback(eventcallback)``
`pyhomematic.devices["FEQ00XXXXX"].setEventCallback(eventcallback)``

**Comment by danielperna84** [comment] 2017-04-29 10:01
The error-value of 2 you get could be a problem. The value 2 stands for `MOTOR_ABORTED`. I don't think that should ever happen in normal operation.

You can leave away the lines with setEventCallback. When you use the lines I told you to enter manually, the callback isn't defined, so you can't set it. What you should try instead is the following:

```python
print(pyhomematic.devices["FEQ00XXXXX"].on())
print(pyhomematic.devices["FEQ00XXXXX"].is_on())
print(pyhomematic.devices["FEQ00XXXXX"].off())
print(pyhomematic.devices["FEQ00XXXXX"].is_off())
```
With those lines you should be able to lock and unlock the device and print out the current state.

**Comment by tringler** [comment] 2017-04-29 12:04
That explains the whole behaviour I guess. As far as I know it's the standard that the switch is not switched if it runs into an error. Let me try to fix it.

**Comment by tringler** [comment] 2017-04-29 20:28
I fixed the error, but unfortunately the switch issue is not fixed. I adjusted the ANGLE_MAX value and it's now working without setting `sensor.feq00xxxxx_error` to value 2. Behaviour in HASS is the same like before.

Tested the script again, but `KeyError: 'FEQ00XXXXX'`
```
import logging
from pyhomematic import HMConnection
logging.basicConfig(level=logging.INFO)
pyhomematic = HMConnection(interface_id="myserver", autostart=True, remotes={"rf":{"ip":"127.0.0.1", "port": 2001}})
print(pyhomematic.devices)
print(pyhomematic.devices["FEQ00XXXXX"].on())
```

**Comment by danielperna84** [comment] 2017-04-29 21:11
Just to verify it's not an operational error: do you have any other switch-devices with which you could verify those few lines of code work? If so, please do that to confirm devices other than the KeyMatic work when switching them manually.

**Comment by tringler** [comment] 2017-04-30 07:11
Just tested it with one of my light switches - Same behaviour.

**Comment by danielperna84** [comment] 2017-04-30 19:42
1. The KeyMatic now works correctly in the HASS UI?
2. In that case there was something you did wrong when accessing the switch / keymatic. Since you've always - for good reason - redacted the device-ID I can't see where the error was. But using the same code works for me. But that doesn't matter anymore if the KeyMatic is now working as it should. :)

**Closed by danielperna84** 2017-04-30 19:42 UTC
Labels: bug

**Comment by tringler** [comment] 2017-04-30 19:48
1. Exactly! Thanks a lot for your support 👍 Like described in this thread locked-state is shown as off and unlocked-state is shown as on, but there a lot of methods to work around in HASS.
2. Yes - I think we don't need to invest more time in my Python problem.
